= Kot-Line Intranet Analyse
:author: CAYE Damien, FALZONE Tonino, NAUGUET Benjamin, DELBOIS Yoan
:docdate: 2022-11-21
:asciidoctor-version:1.1
:description: Projet pédagogique d'initiation à Kotlin
:icons: font
:listing-caption: Listing
:toc-title: Sommaire
:toc: left
:toclevels: 4

== Thème

Développer un Intranet pour une entreprise

== Objectif et Contraintes

Définition du domaine métier représenté par un diagramme de classe des entités métiers.

Choix (et argumentation) de la librairie logicielle que nous avons retenue pour lire un document CSV, à partir de l'article: https://www.baeldung.com/kotlin/csv-files

Définir la façon dont nous comptons implémenter les 3 contraintes de sélection

Présentation de la stratégie retenue par notre équipe concernant la gestion des données à problème.

La façon dont nous envisagons de gérer le cas où l’utilisateur soumet les mêmes données en téléchargement, dans le but d’éviter d’inscrire plusieurs fois les mêmes données dans la base de données.

Identification de risques d’utilisateurs malveillants (Evil User Story ou Abuser Story).

== Solutions

=== Diagramme de classe

=== Librairie Logicielle

=== Implémentation des contraintes de séléctions

=== Gestion des données hors contraintes

=== Twin data
(meme données rentrées par un meme utilisteur)

=== Utilisateurs malveillants


== Fonctionnalitées
Nous avons réunis toutes les fonctionnalitées que devra contenir l'intranet sous forme d'un schéma USE CASE.
 Les fonctionnalités sont associées à l'utilisateur au quel elles sont destinées.
[plantuml]
----

@startuml

left to right direction
skinparam actorStyle awesome
:Gestionnaire: as MyG

package BDD {
(Consulter données) as UC1
(Consulter fichiers) as UC4
(Modifer fichiers) as UC5
(Se connecter) as UC6
(Réaliser stats) as UC7
}

package App_Web {
(Consulter stats) as UC2
(Déposer fichers) as UC3
}

MyG --> UC1
MyG --> UC2
MyG --> UC3
MyG --> UC4
MyG --> UC5
MyG --> UC6
MyG --> UC7



@enduml
----
