= Kot-Line Intranet Analyse
:author: CAYE Damien, FALZONE Tonino, NAUGUET Benjamin, DELBOIS Yoan
:docdate: 2022-11-21
:asciidoctor-version:1.1
:description: Projet pédagogique d'initiation à Kotlin
:icons: font
:listing-caption: Listing
:toc-title: Sommaire
:toc: left
:toclevels: 4

== Thème

Développer un Intranet pour une entreprise. +
(Github : https://github.com/Nenuphare/Kot-Line-Intranet)

== Objectif et Contraintes

Définition du domaine métier représenté par un diagramme de classe des entités métiers.

Choix (et argumentation) de la librairie logicielle que nous avons retenue pour lire un document CSV, à partir de l'article: https://www.baeldung.com/kotlin/csv-files.

Définir la façon dont nous comptons implémenter les 3 contraintes de sélection.

Présentation de la stratégie retenue par notre équipe concernant la gestion des données à problème.

La façon dont nous envisageons de gérer le cas où l’utilisateur soumet les mêmes données en téléchargement, dans le but d’éviter d’inscrire plusieurs fois les mêmes données dans la base de données.

Identification de risques d’utilisateurs malveillants (Evil User Story ou Abuser Story).

== Solutions

=== Diagramme de classe
[plantuml]
----
@startuml

Class Client{
String nom
String prenom
String genre
String email
String dateNaissance
String adresse
String vehicule
Int tel
Double taille
Double poids
Double latitude
Double longitude

}
Class Bancaire{
String CCType
Int CCNum
Int CVV2
String CCExpires
}
Class Véhicule{
Int annee
String modele
}
Class Marque{
String nomMarque
}

Client <|-- Bancaire
Véhicule <|-- Marque

Client "1" *-- "           *" Véhicule



@enduml
----
=== Librairie Logicielle
La librairie logicielle qui permet de lire les fichiers CSV est assez importante, car elle définit la charge de travail à effectuer, mais peut aussi servir à limiter les bugs.

Ainsi la librairie que nous avons choisie est la bibliotèque Apache CSV, car elle est plus efficiente que le traitement avec Kotlin, mais elle est aussi la plus simple à mettre en place comparée à des bibliotèques aussi avancée telle que FasterXML Jacson.

=== Implémentation des contraintes de sélection
Les contraintes de sélection sont au nombre de 3 et sont les suivantes :

* L'âge (18-88 ans)
* La taille des clients
* Le numéro de carte de crédit

Or il y a des problèmes dans les données comme la taille qui ont des unités de mesures différentes selon les clients (Inches et centimètres). +
Il y aura aussi des doublons de numéros de carte de crédit alors que le système ne permet pas le partage de carte de crédit.

Nous avons donc décidé d'implémenter ces contraintes de sélection sur une liste de tous les éléments comme des filtres.
Nous allons traiter les incohérences dans la taille des clients en partant du fait que la taille en centimètre est la bonne taille.
Ainsi nous allons insérer dans la base de donnée la taille en centimètre et convertir cette taille en Inches et s'en servir comme nouvelle valeur de taille en Inches.

Nous allons aussi faire en sorte que les clients qui renseignent une carte deja utilisée par un des utilisateurs ne soit pas enregistrée et la carte doublon sera placée dans un fichier CSV autre.

=== Gestion des données hors contraintes



=== Twin data
(Mêmes données rentrées par un meme utilisateur)

//=== Utilisateurs malveillants


== Fonctionnalités
Nous avons réuni toutes les fonctionnalités que devra contenir l'intranet sous forme d'un schéma USE CASE.
Les fonctionnalités sont associées à l'utilisateur auquel elles sont destinées.
[plantuml]
----

@startuml

left to right direction
skinparam actorStyle awesome
:Gestionnaire: as MyG 

package BDD {
(Consulter données) as UC1
(Consulter fichiers) as UC4
(Modifer fichiers) as UC5
(Se connecter) as UC6
(Réaliser stats) as UC7
(Supprimer fichiers) as UC9
}

package App_Web {
(Consulter stats) as UC2
(Déposer fichers) as UC3
(Consulter fichiers) as UC8
}

MyG --> UC1
MyG --> UC2
MyG --> UC3
MyG --> UC4
MyG --> UC5
MyG --> UC6
MyG --> UC7
MyG --> UC8
MyG --> UC9



@enduml
----
NAUGUET Benjamin, CAYE Damien, FALZONE Tonino, DELBOIS Yoan